name: iptv-ARM64-Release

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: 'iptv-go'
        required: true
        default: 'alpine:latest,alpine/curl,busybox:stable-glibc'

jobs:
  pull_and_package:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Docker Images and Package
        run: |
          images="${{ github.event.inputs.docker_images }}"
          IFS=',' read -r -a image_array <<< "$images"
          for image in "${image_array[@]}"; do
            docker pull "${image}" --platform "linux/arm64"
            image_name="${image//\//_}"
            image_name="${image_name//:/_}"
            docker save "${image}" -o "${image_name}-arm64.tar"
            gzip -c "${image_name}-arm64.tar" > "${image_name}-arm64.tar.gz"
            rm "${image_name}-arm64.tar"
          done

      - name: Download iptv-go.zip from remote URL
        run: |
          curl -L -o iptv-go.zip https://raw.githubusercontent.com/sunyis/dockerdb/refs/heads/master/iptv-go-main.zip 

      - name: List generated files (debug step)
        run: |
          echo "Preparing docker images list (.tar.gz) files:"
          find $GITHUB_WORKSPACE -name "*.tar.gz"
          echo "Preparing iptv-go.zip file:"
          find $GITHUB_WORKSPACE -name "iptv-go.zip"
          release_name=$(TZ="Asia/Shanghai" date +'%Y-%m-%d %H:%M Build')
          echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: DockerTarBuilder-ARM64
          name: ${{ env.RELEASE_NAME }} for ARM64
          body: |
            [![Github](https://img.shields.io/badge/RELEASE:DockerTarBuilder-123456?logo=github&logoColor=fff&labelColor=green&style=for-the-badge)](https://www.bilibili.com/video/BV1EZ421M7mL) [![Github](https://img.shields.io/badge/国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge)](https://wkdaily.cpolar.top/archives/1)
            ### How to use? For example
            `docker load -i alpine_latest.tar.gz `
            ### Video teaching
            [![Bilibili](https://img.shields.io/badge/Bilibili-123456?logo=bilibili&logoColor=fff&labelColor=fb7299)](https://www.bilibili.com/video/BV1yyq6YREdF)
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Upload Docker images as release assets
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: DockerTarBuilder-ARM64
          files: ${{ github.workspace }}/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Upload iptv-go.zip as release asset
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: DockerTarBuilder-ARM64
          files: ${{ github.workspace }}/iptv-go.zip
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
